In [1]:
import numpy as np
import pandas as pd

In [5]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [6]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [9]:
date=date.drop(columns=['product_id' ,'city_id' ,'orders'])

In [10]:
date.head()

         date
0  2019-12-10
1  2018-08-15
2  2018-10-23
3  2019-08-17
4  2019-01-06

In [11]:
time=time.drop(columns=['msg'])
time.head()

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00
2  2012-12-30 00:21:00
3  2014-11-28 00:31:00
4  2013-10-26 23:11:00

In [15]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 7.9 KB

In [16]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
dtypes: str(1)
memory usage: 7.9 KB

In [13]:
# Converting the datatype of date and time

In [12]:
date['date']=pd.to_datetime(date['date'])

In [19]:
time['date']=pd.to_datetime(time['date'])

In [20]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 7.9 KB

## Working with the date

In [33]:
#extract year,month,date:
date['date_year']=date['date'].dt.year
date['date_month']=date['date'].dt.month
date['date_month_name']=date['date'].dt.month_name()
date['date_day']=date['date'].dt.day
date['date_day_name']=date['date'].dt.day_name()
date['day_of_week']=date['date'].dt.dayofweek

date.head()

,date,date_year,date_month,date_day,date_month_name,day_of_week,date_is_weekend,date_day_name
0,2019-12-10,2019,12,10,December,1,0,Tuesday
1,2018-08-15,2018,8,15,August,2,0,Wednesday
2,2018-10-23,2018,10,23,October,1,0,Tuesday
3,2019-08-17,2019,8,17,August,5,0,Saturday
4,2019-01-06,2019,1,6,January,6,0,Sunday

### is this a weekend?

In [36]:
date['date_is_weekend']=np.where(date['date_day_name'].isin(['Friday','Saturday']),1,0)

In [37]:
date.sample(10)

,date,date_year,date_month,date_day,date_month_name,day_of_week,date_is_weekend,date_day_name
954,2019-06-21,2019,6,21,June,4,1,Friday
811,2018-11-03,2018,11,3,November,5,1,Saturday
575,2018-09-27,2018,9,27,September,3,0,Thursday
310,2018-11-20,2018,11,20,November,1,0,Tuesday
65,2019-03-27,2019,3,27,March,2,0,Wednesday
225,2019-04-26,2019,4,26,April,4,1,Friday
262,2018-11-14,2018,11,14,November,2,0,Wednesday
78,2019-05-28,2019,5,28,May,1,0,Tuesday
910,2019-04-25,2019,4,25,April,3,0,Thursday
840,2019-03-29,2019,3,29,March,4,1,Friday