In [1]:
import numpy as np
import pandas as pd

In [5]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [6]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [9]:
date=date.drop(columns=['product_id' ,'city_id' ,'orders'])

In [10]:
date.head()

         date
0  2019-12-10
1  2018-08-15
2  2018-10-23
3  2019-08-17
4  2019-01-06

In [11]:
time=time.drop(columns=['msg'])
time.head()

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00
2  2012-12-30 00:21:00
3  2014-11-28 00:31:00
4  2013-10-26 23:11:00