In [1]:
import numpy as np 
import pandas as pd

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [3]:
df=pd.read_csv("cars.csv")

In [17]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [24]:
df.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [20]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(["selling_price"],axis=1),
                                                       df["selling_price"],
                                                       test_size=.3,
                                                       random_state=42)

In [22]:
X_train.head()

       brand  km_driven    fuel         owner
6783  Maruti     120000  Petrol   Third Owner
1073  Toyota     100000  Diesel   First Owner
7756     BMW      39000  Diesel   First Owner
144   Toyota      39000  Petrol   First Owner
6424  Maruti      70000  Diesel  Second Owner

# ordinal encoding

In [70]:
trf1=ColumnTransformer([
    ('owner',OrdinalEncoder(),[3])
],remainder="passthrough")

In [71]:
X_train.head()

       brand  km_driven    fuel         owner
6783  Maruti     120000  Petrol   Third Owner
1073  Toyota     100000  Diesel   First Owner
7756     BMW      39000  Diesel   First Owner
144   Toyota      39000  Petrol   First Owner
6424  Maruti      70000  Diesel  Second Owner

In [27]:
# One Hot encoding

In [72]:
trf2=ColumnTransformer([
    ('brand_fuel',OneHotEncoder(sparse_output=False,handle_unknown="ignore"),['brand','fuel'])
     ],remainder="passthrough")

In [63]:
# Scaling

In [78]:
trf3=ColumnTransformer([
    ('scaled',MinMaxScaler(),slice(0,8))
])

In [79]:
trf4=SelectKBest(score_func=chi2,k=5)

In [80]:
trf5=DecisionTreeClassifier()

In [81]:
pipe=Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [82]:
pipe.fit(X_train,y_train)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [69]:
X_train.head()

       brand  km_driven    fuel         owner
6783  Maruti     120000  Petrol   Third Owner
1073  Toyota     100000  Diesel   First Owner
7756     BMW      39000  Diesel   First Owner
144   Toyota      39000  Petrol   First Owner
6424  Maruti      70000  Diesel  Second Owner